Handle C macro constants (INT_MAX and INT_MIN) in Fortran bindings
Using fortran_gen.py with the current header files results in errors:

$ python3 tools/fortran_gen.py  --prefix include/  include/plasma*h
Exported file: include/plasma_mod.f90
$ gfortran -c -o include/plasma_mod.o include/plasma_mod.f90
include/plasma_mod.f90:33:57:

   33 |     integer, parameter :: PlasmaDatatypeUnknown = INT_MIN
      |                                                         1
Error: Symbol ‘int_min’ at (1) has no IMPLICIT type
<snip>
include/plasma_mod.f90:88:54:
   88 |     integer, parameter :: PlasmaInoutUnknown = INT_MAX
      |                                                      1
Error: Symbol ‘int_max’ at (1) has no IMPLICIT type; did you mean ‘c_intmax_t’?
<snip>

With this change INT_MAX is converted to c_intmax_t and INT_MIN to -c_intmax_t.

Signed-off-by: Adrian Reber <areber@redhat.com>

* Add translation of constants defined by macros

---------

Signed-off-by: Adrian Reber <areber@redhat.com>
Co-authored-by: Piotr Luszczek <luszczek@icl.utk.edu>