tools: handle INT_MAX and INT_MIN in fortran_gen.py
Using fortran_gen.py with the current header files results in errors:

$ python3 tools/fortran_gen.py  --prefix include/  include/plasma*h
Exported file: include/plasma_mod.f90
$ gfortran -c -o include/plasma_mod.o include/plasma_mod.f90
include/plasma_mod.f90:33:57:

   33 |     integer, parameter :: PlasmaDatatypeUnknown = INT_MIN
      |                                                         1
Error: Symbol ‘int_min’ at (1) has no IMPLICIT type
include/plasma_mod.f90:72:54:

   72 |     integer, parameter :: PlasmaConstUnknown = INT_MIN
      |                                                      1
Error: Symbol ‘int_min’ at (1) has no IMPLICIT type
include/plasma_mod.f90:84:54:

   84 |     integer, parameter :: PlasmaErrorUnknown = INT_MIN
      |                                                      1
Error: Symbol ‘int_min’ at (1) has no IMPLICIT type
include/plasma_mod.f90:88:54:

   88 |     integer, parameter :: PlasmaInoutUnknown = INT_MAX
      |                                                      1
Error: Symbol ‘int_max’ at (1) has no IMPLICIT type; did you mean ‘c_intmax_t’?
include/plasma_mod.f90:92:60:

   92 |     integer, parameter :: PlasmaHouseholderUnknown = INT_MAX
      |                                                            1
Error: Symbol ‘int_max’ at (1) has no IMPLICIT type; did you mean ‘c_intmax_t’?
include/plasma_mod.f90:96:54:

   96 |     integer, parameter :: PlasmaAbledUnknown = INT_MAX
      |                                                      1
Error: Symbol ‘int_max’ at (1) has no IMPLICIT type; did you mean ‘c_intmax_t’?
include/plasma_mod.f90:104:54:

  104 |     integer, parameter :: PlasmaParamUnknown = INT_MAX
      |                                                      1
Error: Symbol ‘int_max’ at (1) has no IMPLICIT type; did you mean ‘c_intmax_t’?

With this change INT_MAX is converted to c_intmax_t and INT_MIN to -c_intmax_t.

Signed-off-by: Adrian Reber <areber@redhat.com>